name: ci
on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install pip dependencies
        run: |
          pip install --upgrade pip
          pip install robotframework
          pip install --upgrade RESTinstance
          pip install --upgrade robotframework-seleniumlibrary
      - name: Run Test
        run: python -m robot --outputdir results Tests/API
      - name: Publish test results
        uses: actions/upload-artifact@v2
        with:
          name: robot-test-results
          path: results
